# Generated by Django 4.0.2 on 2022-03-04 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('company_address', models.TextField()),
                ('company_area_of_interest', models.TextField()),
                ('current_plan', models.CharField(max_length=30)),
                ('registerd_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('registerd_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
