# Generated by Django 4.0.2 on 2022-03-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sponsors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsors',
            new_name='Sponsor',
        ),
    ]
