# Generated by Django 4.0.2 on 2022-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_age_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.TextField(default=34444444, unique=True),
            preserve_default=False,
        ),
    ]
