# Generated by Django 4.0.2 on 2022-04-23 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='connect',
            new_name='jobRole',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebookHandle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedInHandle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.ImageField(default='hh', upload_to='user/profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitterHandle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
