# Generated by Django 4.0.2 on 2022-04-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_connect_profile_jobrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='user/resume'),
        ),
    ]
