# Generated by Django 4.0.2 on 2022-03-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('isBusiness', models.BooleanField(default=False)),
                ('company_name', models.TextField()),
                ('company_location', models.TextField()),
                ('nature_of_job', models.TextField()),
                ('skills', models.TextField()),
                ('academic_qualification', models.TextField()),
                ('gender', models.TextField()),
                ('age_bracket', models.TextField()),
                ('years_of_experience', models.TextField()),
                ('job_description', models.TextField()),
                ('other_benefits', models.TextField()),
                ('salary_range', models.TextField()),
                ('application_deadline', models.TextField()),
            ],
        ),
    ]
