# Generated by Django 4.0.2 on 2022-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_assignment_description_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='material_type',
            field=models.TextField(default='assignment'),
        ),
        migrations.AddField(
            model_name='topic',
            name='material_type',
            field=models.TextField(default='topic'),
        ),
    ]
