# Generated by Django 4.0.2 on 2022-03-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email_address',
            field=models.EmailField(default='morganhezekiah11@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='company_mobile_contact',
            field=models.CharField(default='0900', max_length=40),
        ),
    ]
