# Generated by Django 4.0.2 on 2022-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_mobile_contact',
            field=models.CharField(max_length=40),
        ),
    ]
