# Generated by Django 4.0.2 on 2022-03-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_registerd_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='registerd_by',
            new_name='registered_by',
        ),
    ]
