# Generated by Django 4.0.2 on 2022-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_registerd_by_company_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_current_plan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
