# Generated by Django 4.0.2 on 2022-03-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_company_current_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_description',
        ),
    ]
