# Generated by Django 4.0.2 on 2022-03-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_company_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_slug',
            field=models.TextField(default='fdtgejekue6ffrur7rmru', unique=True),
            preserve_default=False,
        ),
    ]
