# Generated by Django 4.0.2 on 2022-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_slug',
            field=models.TextField(),
        ),
    ]
