"""
Django settings for jh project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import django_heroku
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&&pp%_d*5zw(hvmz!*u@#ljf!ubiock*b!yaseqf-9f-n*nv#h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["https://owerri-job-hunt-backend.herokuapp.com", "http://127.0.0.1:8000","http://localhost:8000"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     "corsheaders",
     "emails",
     "users",
     "topics",
     "jobs",
     "companies",
     'rest_framework',
     'knox',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'jh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),

}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL ="users.User"

JWT_SECRET ="n8l1v4h3g0t1f6h5p5p9n9d9z5y1q4j6y3q3n8k7k1w7x5y6l8o2f3j8g3s1e3f4i4v1"
JWT_ALGORITHM ="HS256"

# EMAIL_USE_TLS = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_PASSWORD="wmiixksozsqletoc"
# EMAIL_HOST_USER="morganhezekiah11@gmail.com"
# EMAIL_PORT = 587
# DEFAULT_FROM_EMAIL = 'Dont Reply <do_not_reply@owerrijobhunt.ng>'


# AWS SES
# EMAIL_USE_TLS = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'email-smtp.eu-west-3.amazonaws.com'
# EMAIL_HOST_PASSWORD="BAgznc58HWnGtw+WXB6ygExYpiYw8tWrakNDeA6xhz9M"
# EMAIL_HOST_USER="AKIAQKBOBJPZJRMG3K5U"
# EMAIL_PORT = 587
# DEFAULT_FROM_EMAIL = 'owerrijobhunt'


#MAILTRAP.IO
# EMAIL_USE_TLS = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.mailtrap.io'
# EMAIL_HOST_USER = '80eea23ff69ff7'
# EMAIL_HOST_PASSWORD = 'c56df7b0b99533'
# EMAIL_PORT = '2525'
# DEFAULT_FROM_EMAIL = 'owerrijobhunt'

##SENDGRID
# EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND")
# EMAIL_HOST = str(os.environ.get("EMAIL_HOST"))
# EMAIL_HOST_USER = str(os.environ.get("EMAIL_HOST_USER"))
# EMAIL_HOST_PASSWORD = str(os.environ.get("EMAIL_HOST_PASSWORD"))
# EMAIL_PORT = str(os.environ.get("EMAIL_PORT"))
# DEFAULT_FROM_EMAIL=str(os.environ.get("DEFAULT_FROM_EMAIL"))


# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:3000",
#     "http://localhost:3000",
#     "https://622a26c8abc2d86b110f5fab--festive-booth-d4c8ec.netlify.app",
#     "http://622a26c8abc2d86b110f5fab--festive-booth-d4c8ec.netlify.app"
# ]


CORS_ALLOW_ALL_ORIGINS =True

# CORS_ORIGIN_WHITELIST = [
#      "http://127.0.0.1:3000",
#     "http://localhost:3000"
# ]


CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

django_heroku.settings(locals(), staticfiles=False)
